/*
 INTEGRANTES: Argenis Adán Gutiérrez Hurtado, Gerardo Josue Rubio Calderon, Pablo Becerra Bedoy
*/
package act1_lexico;

import java_cup.runtime.*;

/* TERMINALES DE KOTLIN */
terminal VAL, VAR, FUN, CLASS, INTERFACE, OBJECT, TYPEALIAS, TYPEOF,
         IF, ELSE, WHEN, WHILE, FOR, DO, RETURN, BREAK, CONTINUE,
         PACKAGE, IMPORT, TRY, CATCH, FINALLY, THROW,
         PUBLIC, PRIVATE, PROTECTED, INTERNAL,
         ABSTRACT, FINAL, OPEN, OVERRIDE, SEALED, DATA, ENUM, INNER, VALUE, ANNOTATION,
         INFIX, OPERATOR, INLINE, NOINLINE, CROSSINLINE, TAILREC, EXTERNAL, LATEINIT, VARARG, SUSPEND, CONST,
         IS, NOT_IS, AS, AS_SAFE, IN, NOT_IN,
         THIS, SUPER, NULL, TRUE, FALSE,
         BY, GET, SET, FIELD, FILE, GETTER, SETTER, PROPERTY, RECEIVER, PARAM, SETPARAM, DELEGATE,
         CONSTRUCTOR, INIT, COMPANION, EXPECT, ACTUAL,
         DYNAMIC, REIFIED, WHERE, OUT,
         PLUS, MINUS, MULT, DIV, MOD,
         EQ, EQEQ, NEQ, LT, LE, GT, GE, EQEQEQ, NEQEQEQ,
         AND, OR, NOT, SAFE_CALL, ELVIS, RANGE, DOUBLE_COLON,
         LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK,
         COMMA, SEMICOLON, DOT, COLON;

/* TERMINALES - VALORES Y ERRORES */
terminal String IDENTIFIER, INT_LITERAL, LONG_LITERAL, FLOAT_LITERAL, DOUBLE_LITERAL, CHAR_LITERAL, STRING_LITERAL, ERROR;

/* NO TERMINALES */
non terminal archivo, paquete_opt, importacion_list, paquete, importacion, ubicacion, clase_principal, identificador;

/* REGLA INICIAL */
start with archivo;

/* REGLAS GRAMATICALES */

archivo ::= paquete_opt importacion_list clase_principal
    {: System.out.println("Regla reconocida: archivo"); :};

paquete_opt ::= paquete
    | /* vacio */;

importacion_list ::= importacion_list importacion
    | /* vacio */;

paquete ::= PACKAGE:p ubicacion SEMICOLON
    {: System.out.println("Regla reconocida: paquete (Linea " + pleft + ")"); :};

importacion ::= IMPORT:i ubicacion SEMICOLON
    {: System.out.println("Regla reconocida: importacion (Linea " + ileft + ")"); :};

ubicacion ::= identificador DOT ubicacion
    | identificador
    {: System.out.println("Regla reconocida: ubicacion"); :};

clase_principal ::= CLASS:c identificador LBRACE RBRACE
    {: System.out.println("Regla reconocida: clase_principal (Linea " + cleft + ")"); :};

identificador ::= IDENTIFIER
    {: System.out.println("Regla reconocida: identificador"); :};