// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/act1_lexico/java_lexico.jflex

package act1_lexico;

import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class LexerJava implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\11\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\0\5\31\1\32"+
    "\24\31\1\33\1\34\1\35\1\0\1\31\1\0\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\31"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\1\31\1\66\1\67\1\70\7\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\1\1\1\24"+
    "\1\25\1\26\20\24\1\27\1\1\1\30\1\31\2\0"+
    "\1\32\1\33\1\0\1\34\4\5\1\35\1\0\1\2"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\3\24\1\47\6\24\1\50\7\24\1\51\1\24"+
    "\1\52\1\53\23\24\1\54\1\55\1\56\1\57\1\60"+
    "\1\5\1\60\2\0\1\61\1\36\1\62\3\24\1\63"+
    "\15\24\1\64\1\65\13\24\1\66\15\24\1\67\1\24"+
    "\1\70\1\71\2\24\1\0\1\2\1\0\1\61\1\0"+
    "\12\24\1\72\1\73\1\74\6\24\1\75\5\24\1\76"+
    "\1\24\1\77\13\24\1\100\1\24\1\101\3\24\1\102"+
    "\2\24\1\103\3\24\1\104\1\105\1\106\1\24\1\107"+
    "\4\24\1\110\1\111\1\24\1\112\1\24\1\113\14\24"+
    "\1\114\2\24\1\115\2\24\1\116\1\24\1\117\1\120"+
    "\1\24\1\121\5\24\1\122\2\24\1\123\1\124\4\24"+
    "\1\125\5\24\1\126\1\127\1\130\3\24\1\131\1\132"+
    "\7\24\1\133\6\24\1\134\1\135\1\24\1\136\1\137"+
    "\1\24\1\140\3\24\1\141\1\24\1\142\1\24\1\143"+
    "\1\144\1\145\1\146\1\147\3\24\1\150\2\24\1\151"+
    "\1\152\1\153\1\154\2\24\1\155\1\156";

  private static int [] zzUnpackAction() {
    int [] result = new int[343];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\71\0\u011d\0\u0156"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\u018f\0\u01c8"+
    "\0\u0201\0\u023a\0\u0273\0\71\0\u02ac\0\u02e5\0\u031e\0\u0357"+
    "\0\u0390\0\71\0\71\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad"+
    "\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675"+
    "\0\u06ae\0\u06e7\0\u0720\0\71\0\u0759\0\71\0\u0792\0\u07cb"+
    "\0\344\0\71\0\71\0\u0804\0\71\0\u083d\0\u0876\0\u08af"+
    "\0\u08e8\0\71\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05\0\71"+
    "\0\71\0\u0a3e\0\71\0\71\0\71\0\u0a77\0\u0ab0\0\u0ae9"+
    "\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0390"+
    "\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0390"+
    "\0\u0e40\0\u0e79\0\u0390\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96"+
    "\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e"+
    "\0\u1197\0\u11d0\0\u1209\0\u1242\0\u127b\0\u12b4\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\u08af\0\u12ed\0\u1326\0\u135f"+
    "\0\u1398\0\71\0\u13d1\0\u140a\0\u1443\0\71\0\u147c\0\u14b5"+
    "\0\u14ee\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d"+
    "\0\u16b6\0\u16ef\0\u1728\0\u0390\0\u0390\0\u1761\0\u179a\0\u17d3"+
    "\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u1929\0\u1962\0\u199b"+
    "\0\u0390\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8\0\u1af1\0\u1b2a"+
    "\0\u1b63\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c47\0\u1c80\0\u0390\0\u1cb9"+
    "\0\u1cf2\0\u1d2b\0\u1d64\0\u1d9d\0\u1dd6\0\71\0\u1e0f\0\71"+
    "\0\u1e48\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65\0\u1f9e\0\u1fd7"+
    "\0\u2010\0\u2049\0\u2082\0\u0390\0\u0390\0\u0390\0\u20bb\0\u20f4"+
    "\0\u212d\0\u2166\0\u219f\0\u21d8\0\u0390\0\u2211\0\u224a\0\u2283"+
    "\0\u22bc\0\u22f5\0\u0390\0\u232e\0\u0390\0\u2367\0\u23a0\0\u23d9"+
    "\0\u2412\0\u244b\0\u2484\0\u24bd\0\u24f6\0\u252f\0\u2568\0\u25a1"+
    "\0\u0390\0\u25da\0\u0390\0\u2613\0\u264c\0\u2685\0\u0390\0\u26be"+
    "\0\u26f7\0\u1e0f\0\u2730\0\u2769\0\u27a2\0\u0390\0\u0390\0\u0390"+
    "\0\u27db\0\u2814\0\u284d\0\u2886\0\u28bf\0\u28f8\0\u0390\0\u2931"+
    "\0\u296a\0\u0390\0\u29a3\0\u0390\0\u29dc\0\u2a15\0\u2a4e\0\u2a87"+
    "\0\u2ac0\0\u2af9\0\u2b32\0\u2b6b\0\u2ba4\0\u2bdd\0\u2c16\0\u2c4f"+
    "\0\u0390\0\u2c88\0\u2cc1\0\u0390\0\u2cfa\0\u2d33\0\u0390\0\u2d6c"+
    "\0\u0390\0\u0390\0\u2da5\0\u0390\0\u2dde\0\u2e17\0\u2e50\0\u2e89"+
    "\0\u2ec2\0\u0390\0\u2efb\0\u2f34\0\u0390\0\u0390\0\u2f6d\0\u2fa6"+
    "\0\u2fdf\0\u3018\0\u0390\0\u3051\0\u308a\0\u30c3\0\u30fc\0\u3135"+
    "\0\u0390\0\u0390\0\u0390\0\u316e\0\u31a7\0\u31e0\0\u0390\0\u0390"+
    "\0\u3219\0\u3252\0\u328b\0\u32c4\0\u32fd\0\u3336\0\u336f\0\u0390"+
    "\0\u33a8\0\u33e1\0\u341a\0\u3453\0\u348c\0\u34c5\0\u0390\0\u0390"+
    "\0\u34fe\0\u0390\0\u0390\0\u3537\0\u0390\0\u3570\0\u35a9\0\u35e2"+
    "\0\u0390\0\u361b\0\u0390\0\u3654\0\u0390\0\u0390\0\u0390\0\u0390"+
    "\0\u0390\0\u368d\0\u36c6\0\u36ff\0\u0390\0\u3738\0\u3771\0\u0390"+
    "\0\u0390\0\u0390\0\u0390\0\u37aa\0\u37e3\0\u0390\0\u0390";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[343];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\2\31\1\32\1\2\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\2\31\1\42\2\31\1\43\1\31\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\31\1\52\1\53"+
    "\2\31\1\54\1\55\1\56\72\0\2\3\114\0\1\57"+
    "\17\0\1\60\22\0\2\61\1\62\2\61\1\63\26\61"+
    "\1\64\34\61\7\0\1\65\61\0\2\66\1\0\1\67"+
    "\4\66\1\70\23\66\1\71\34\66\17\0\1\72\64\0"+
    "\1\73\4\0\1\74\67\0\1\75\1\0\2\76\6\0"+
    "\2\77\3\0\30\77\22\0\1\75\1\0\2\22\6\0"+
    "\2\77\3\0\30\77\26\0\1\100\73\0\1\101\70\0"+
    "\1\102\70\0\1\103\61\0\1\104\3\0\1\105\66\0"+
    "\2\31\6\0\2\31\3\0\30\31\24\0\2\31\6\0"+
    "\2\31\3\0\1\31\1\106\1\107\12\31\1\110\3\31"+
    "\1\111\6\31\24\0\2\31\6\0\2\31\3\0\20\31"+
    "\1\112\7\31\24\0\2\31\6\0\2\31\3\0\1\113"+
    "\12\31\1\114\2\31\1\115\1\31\1\116\7\31\24\0"+
    "\2\31\6\0\2\31\3\0\1\117\15\31\1\120\11\31"+
    "\24\0\2\31\6\0\2\31\3\0\13\31\1\121\1\31"+
    "\1\122\10\31\1\123\1\31\24\0\2\31\6\0\2\31"+
    "\3\0\1\124\7\31\1\125\5\31\1\126\4\31\1\127"+
    "\4\31\24\0\2\31\6\0\2\31\3\0\5\31\1\130"+
    "\6\31\1\131\1\132\3\31\1\133\6\31\24\0\2\31"+
    "\6\0\2\31\3\0\1\134\27\31\24\0\2\31\6\0"+
    "\2\31\3\0\16\31\1\135\4\31\1\136\4\31\24\0"+
    "\2\31\6\0\2\31\3\0\1\31\1\137\15\31\1\140"+
    "\3\31\1\141\1\142\3\31\24\0\2\31\6\0\2\31"+
    "\3\0\1\143\17\31\1\144\2\31\1\145\4\31\24\0"+
    "\2\31\6\0\2\31\3\0\4\31\1\146\23\31\24\0"+
    "\2\31\6\0\2\31\3\0\4\31\1\147\16\31\1\150"+
    "\4\31\24\0\2\31\6\0\2\31\3\0\1\151\6\31"+
    "\1\152\10\31\1\153\6\31\1\154\24\0\2\31\6\0"+
    "\2\31\3\0\1\155\27\31\24\0\2\31\6\0\2\31"+
    "\3\0\7\31\1\156\20\31\72\0\1\157\27\0\1\160"+
    "\115\0\1\161\3\0\1\162\11\0\2\61\2\0\65\61"+
    "\2\67\1\0\5\67\1\163\62\67\1\0\5\67\1\164"+
    "\60\67\10\0\1\163\60\0\2\66\1\0\1\67\4\66"+
    "\1\165\60\66\13\166\1\167\55\166\2\74\2\0\65\74"+
    "\21\0\2\170\65\0\1\171\1\0\2\76\6\0\2\77"+
    "\3\0\30\77\34\0\2\77\3\0\30\77\31\0\1\172"+
    "\63\0\2\31\6\0\2\31\3\0\21\31\1\173\6\31"+
    "\24\0\2\31\6\0\2\31\3\0\22\31\1\174\5\31"+
    "\24\0\2\31\6\0\2\31\3\0\15\31\1\175\12\31"+
    "\24\0\2\31\5\0\1\176\2\31\3\0\30\31\24\0"+
    "\2\31\6\0\2\31\3\0\4\31\1\177\23\31\24\0"+
    "\2\31\6\0\2\31\3\0\22\31\1\200\5\31\24\0"+
    "\2\31\6\0\2\31\3\0\1\201\27\31\24\0\2\31"+
    "\6\0\2\31\3\0\14\31\1\202\1\203\12\31\24\0"+
    "\2\31\6\0\2\31\3\0\16\31\1\204\11\31\24\0"+
    "\2\31\6\0\2\31\3\0\22\31\1\205\5\31\24\0"+
    "\2\31\6\0\2\31\3\0\21\31\1\206\6\31\24\0"+
    "\2\31\6\0\2\31\3\0\23\31\1\207\4\31\24\0"+
    "\2\31\6\0\2\31\3\0\17\31\1\210\2\31\1\211"+
    "\5\31\24\0\2\31\6\0\2\31\3\0\13\31\1\212"+
    "\14\31\24\0\2\31\6\0\2\31\3\0\15\31\1\213"+
    "\12\31\24\0\2\31\6\0\2\31\3\0\20\31\1\214"+
    "\7\31\24\0\2\31\6\0\2\31\3\0\15\31\1\215"+
    "\12\31\24\0\2\31\6\0\2\31\3\0\17\31\1\216"+
    "\10\31\24\0\2\31\6\0\2\31\3\0\5\31\1\217"+
    "\2\31\1\220\2\31\1\221\1\31\1\222\4\31\1\223"+
    "\5\31\24\0\2\31\6\0\2\31\3\0\22\31\1\224"+
    "\5\31\24\0\2\31\6\0\2\31\3\0\10\31\1\225"+
    "\17\31\24\0\2\31\6\0\2\31\3\0\13\31\1\226"+
    "\14\31\24\0\2\31\6\0\2\31\3\0\11\31\1\227"+
    "\16\31\24\0\2\31\6\0\2\31\3\0\4\31\1\230"+
    "\23\31\24\0\2\31\6\0\2\31\3\0\22\31\1\231"+
    "\5\31\24\0\2\31\6\0\2\31\3\0\4\31\1\232"+
    "\23\31\24\0\2\31\6\0\2\31\3\0\2\31\1\233"+
    "\25\31\24\0\2\31\6\0\2\31\3\0\10\31\1\234"+
    "\5\31\1\235\11\31\24\0\2\31\6\0\2\31\3\0"+
    "\1\31\1\236\26\31\24\0\2\31\6\0\2\31\3\0"+
    "\22\31\1\237\5\31\24\0\2\31\6\0\2\31\3\0"+
    "\1\240\27\31\24\0\2\31\6\0\2\31\3\0\17\31"+
    "\1\241\1\31\1\242\6\31\24\0\2\31\6\0\2\31"+
    "\3\0\10\31\1\243\17\31\24\0\2\31\6\0\2\31"+
    "\3\0\10\31\1\244\7\31\1\245\7\31\24\0\2\31"+
    "\6\0\2\31\3\0\23\31\1\246\3\31\1\247\24\0"+
    "\2\31\6\0\2\31\3\0\17\31\1\250\10\31\24\0"+
    "\2\31\6\0\2\31\3\0\13\31\1\251\4\31\1\252"+
    "\7\31\24\0\2\31\6\0\2\31\3\0\4\31\1\253"+
    "\3\31\1\254\17\31\3\0\13\166\1\255\55\166\13\0"+
    "\1\167\4\0\1\256\67\0\1\257\1\0\2\170\7\0"+
    "\1\260\10\0\1\260\46\0\2\261\67\0\2\31\6\0"+
    "\2\31\3\0\22\31\1\262\5\31\24\0\2\31\6\0"+
    "\2\31\3\0\23\31\1\263\4\31\24\0\2\31\6\0"+
    "\2\31\3\0\16\31\1\264\11\31\24\0\2\31\6\0"+
    "\2\31\3\0\1\265\27\31\24\0\2\31\6\0\2\31"+
    "\3\0\2\31\1\266\25\31\24\0\2\31\6\0\2\31"+
    "\3\0\21\31\1\267\6\31\24\0\2\31\6\0\2\31"+
    "\3\0\17\31\1\270\10\31\24\0\2\31\6\0\2\31"+
    "\3\0\21\31\1\271\1\272\5\31\24\0\2\31\6\0"+
    "\2\31\3\0\21\31\1\273\6\31\24\0\2\31\6\0"+
    "\2\31\3\0\1\274\27\31\24\0\2\31\6\0\2\31"+
    "\3\0\4\31\1\275\23\31\24\0\2\31\6\0\2\31"+
    "\3\0\14\31\1\276\13\31\24\0\2\31\6\0\2\31"+
    "\3\0\4\31\1\277\23\31\24\0\2\31\6\0\2\31"+
    "\3\0\4\31\1\300\23\31\24\0\2\31\6\0\2\31"+
    "\3\0\21\31\1\301\6\31\24\0\2\31\6\0\2\31"+
    "\3\0\1\302\27\31\24\0\2\31\6\0\2\31\3\0"+
    "\16\31\1\303\11\31\24\0\2\31\6\0\2\31\3\0"+
    "\10\31\1\304\17\31\24\0\2\31\6\0\2\31\3\0"+
    "\22\31\1\305\5\31\24\0\2\31\6\0\2\31\3\0"+
    "\10\31\1\306\17\31\24\0\2\31\6\0\2\31\3\0"+
    "\4\31\1\307\23\31\24\0\2\31\6\0\2\31\3\0"+
    "\4\31\1\310\23\31\24\0\2\31\6\0\2\31\3\0"+
    "\4\31\1\311\23\31\24\0\2\31\6\0\2\31\3\0"+
    "\15\31\1\312\12\31\24\0\2\31\6\0\2\31\3\0"+
    "\13\31\1\313\14\31\24\0\2\31\6\0\2\31\3\0"+
    "\4\31\1\314\23\31\24\0\2\31\6\0\2\31\3\0"+
    "\15\31\1\315\2\31\1\316\7\31\24\0\2\31\6\0"+
    "\2\31\3\0\20\31\1\317\7\31\24\0\2\31\6\0"+
    "\2\31\3\0\12\31\1\320\15\31\24\0\2\31\6\0"+
    "\2\31\3\0\24\31\1\321\3\31\24\0\2\31\6\0"+
    "\2\31\3\0\22\31\1\322\5\31\24\0\2\31\6\0"+
    "\2\31\3\0\13\31\1\323\14\31\24\0\2\31\6\0"+
    "\2\31\3\0\23\31\1\324\4\31\24\0\2\31\6\0"+
    "\2\31\3\0\13\31\1\325\14\31\24\0\2\31\6\0"+
    "\2\31\3\0\4\31\1\326\23\31\24\0\2\31\6\0"+
    "\2\31\3\0\17\31\1\327\10\31\24\0\2\31\6\0"+
    "\2\31\3\0\13\31\1\330\14\31\24\0\2\31\6\0"+
    "\2\31\3\0\21\31\1\331\6\31\24\0\2\31\6\0"+
    "\2\31\3\0\16\31\1\332\11\31\24\0\2\31\6\0"+
    "\2\31\3\0\4\31\1\333\23\31\24\0\2\31\6\0"+
    "\2\31\3\0\4\31\1\334\23\31\24\0\2\31\6\0"+
    "\2\31\3\0\23\31\1\335\4\31\24\0\2\31\6\0"+
    "\2\31\3\0\1\336\27\31\24\0\2\31\6\0\2\31"+
    "\3\0\15\31\1\337\2\31\1\340\7\31\24\0\2\31"+
    "\6\0\2\31\3\0\13\31\1\341\14\31\3\0\13\166"+
    "\1\255\4\166\1\256\50\166\21\0\2\342\65\0\1\257"+
    "\1\0\2\261\67\0\2\31\6\0\2\31\3\0\20\31"+
    "\1\343\7\31\24\0\2\31\6\0\2\31\3\0\1\344"+
    "\27\31\24\0\2\31\6\0\2\31\3\0\22\31\1\345"+
    "\5\31\24\0\2\31\6\0\2\31\3\0\12\31\1\346"+
    "\15\31\24\0\2\31\6\0\2\31\3\0\7\31\1\347"+
    "\20\31\24\0\2\31\6\0\2\31\3\0\21\31\1\350"+
    "\6\31\24\0\2\31\6\0\2\31\3\0\1\351\27\31"+
    "\24\0\2\31\6\0\2\31\3\0\22\31\1\352\5\31"+
    "\24\0\2\31\6\0\2\31\3\0\10\31\1\353\17\31"+
    "\24\0\2\31\6\0\2\31\3\0\21\31\1\354\6\31"+
    "\24\0\2\31\6\0\2\31\3\0\2\31\1\355\25\31"+
    "\24\0\2\31\6\0\2\31\3\0\20\31\1\356\7\31"+
    "\24\0\2\31\6\0\2\31\3\0\4\31\1\357\23\31"+
    "\24\0\2\31\6\0\2\31\3\0\13\31\1\360\14\31"+
    "\24\0\2\31\6\0\2\31\3\0\20\31\1\361\7\31"+
    "\24\0\2\31\6\0\2\31\3\0\26\31\1\362\1\31"+
    "\24\0\2\31\6\0\2\31\3\0\15\31\1\363\12\31"+
    "\24\0\2\31\6\0\2\31\3\0\20\31\1\364\7\31"+
    "\24\0\2\31\6\0\2\31\3\0\20\31\1\365\7\31"+
    "\24\0\2\31\6\0\2\31\3\0\10\31\1\366\17\31"+
    "\24\0\2\31\6\0\2\31\3\0\13\31\1\367\14\31"+
    "\24\0\2\31\6\0\2\31\3\0\2\31\1\370\25\31"+
    "\24\0\2\31\6\0\2\31\3\0\1\371\27\31\24\0"+
    "\2\31\6\0\2\31\3\0\20\31\1\372\7\31\24\0"+
    "\2\31\6\0\2\31\3\0\1\373\27\31\24\0\2\31"+
    "\6\0\2\31\3\0\1\374\27\31\24\0\2\31\6\0"+
    "\2\31\3\0\4\31\1\375\23\31\24\0\2\31\6\0"+
    "\2\31\3\0\10\31\1\376\17\31\24\0\2\31\6\0"+
    "\2\31\3\0\20\31\1\377\7\31\24\0\2\31\6\0"+
    "\2\31\3\0\4\31\1\u0100\23\31\24\0\2\31\6\0"+
    "\2\31\3\0\20\31\1\u0101\7\31\24\0\2\31\6\0"+
    "\2\31\3\0\4\31\1\u0102\23\31\24\0\2\31\6\0"+
    "\2\31\3\0\20\31\1\u0103\7\31\24\0\2\31\6\0"+
    "\2\31\3\0\25\31\1\u0104\2\31\24\0\2\31\6\0"+
    "\2\31\3\0\1\u0105\15\31\1\u0106\11\31\24\0\2\31"+
    "\6\0\2\31\3\0\4\31\1\u0107\23\31\24\0\2\31"+
    "\6\0\2\31\3\0\20\31\1\u0108\7\31\24\0\2\31"+
    "\6\0\2\31\3\0\4\31\1\u0109\23\31\24\0\2\31"+
    "\6\0\2\31\3\0\4\31\1\u010a\23\31\24\0\2\31"+
    "\6\0\2\31\3\0\1\u010b\27\31\24\0\2\31\6\0"+
    "\2\31\3\0\13\31\1\u010c\14\31\24\0\2\31\6\0"+
    "\2\31\3\0\1\u010d\27\31\24\0\2\31\6\0\2\31"+
    "\3\0\15\31\1\u010e\12\31\24\0\2\31\6\0\2\31"+
    "\3\0\20\31\1\u010f\7\31\24\0\2\31\6\0\2\31"+
    "\3\0\15\31\1\u0110\12\31\24\0\2\31\6\0\2\31"+
    "\3\0\10\31\1\u0111\17\31\24\0\2\31\6\0\2\31"+
    "\3\0\22\31\1\u0112\5\31\24\0\2\31\6\0\2\31"+
    "\3\0\15\31\1\u0113\12\31\24\0\2\31\6\0\2\31"+
    "\3\0\13\31\1\u0114\14\31\24\0\2\31\6\0\2\31"+
    "\3\0\22\31\1\u0115\5\31\24\0\2\31\6\0\2\31"+
    "\3\0\4\31\1\u0116\23\31\24\0\2\31\6\0\2\31"+
    "\3\0\5\31\1\u0117\7\31\1\u0118\12\31\24\0\2\31"+
    "\6\0\2\31\3\0\15\31\1\u0119\12\31\24\0\2\31"+
    "\6\0\2\31\3\0\10\31\1\u011a\17\31\24\0\2\31"+
    "\6\0\2\31\3\0\22\31\1\u011b\5\31\24\0\2\31"+
    "\6\0\2\31\3\0\22\31\1\u011c\5\31\24\0\2\31"+
    "\6\0\2\31\3\0\10\31\1\u011d\17\31\24\0\2\31"+
    "\6\0\2\31\3\0\6\31\1\u011e\21\31\24\0\2\31"+
    "\6\0\2\31\3\0\22\31\1\u011f\5\31\24\0\2\31"+
    "\6\0\2\31\3\0\2\31\1\u0120\25\31\24\0\2\31"+
    "\6\0\2\31\3\0\2\31\1\u0121\25\31\24\0\2\31"+
    "\6\0\2\31\3\0\15\31\1\u0122\12\31\24\0\2\31"+
    "\6\0\2\31\3\0\3\31\1\u0123\24\31\24\0\2\31"+
    "\6\0\2\31\3\0\15\31\1\u0124\12\31\24\0\2\31"+
    "\6\0\2\31\3\0\4\31\1\u0125\23\31\24\0\2\31"+
    "\6\0\2\31\3\0\13\31\1\u0126\14\31\24\0\2\31"+
    "\6\0\2\31\3\0\5\31\1\u0127\22\31\24\0\2\31"+
    "\6\0\2\31\3\0\6\31\1\u0128\21\31\24\0\2\31"+
    "\6\0\2\31\3\0\2\31\1\u0129\25\31\24\0\2\31"+
    "\6\0\2\31\3\0\22\31\1\u012a\5\31\24\0\2\31"+
    "\6\0\2\31\3\0\10\31\1\u012b\17\31\24\0\2\31"+
    "\6\0\2\31\3\0\23\31\1\u012c\4\31\24\0\2\31"+
    "\6\0\2\31\3\0\23\31\1\u012d\4\31\24\0\2\31"+
    "\6\0\2\31\3\0\15\31\1\u012e\12\31\24\0\2\31"+
    "\6\0\2\31\3\0\1\u012f\27\31\24\0\2\31\6\0"+
    "\2\31\3\0\27\31\1\u0130\24\0\2\31\6\0\2\31"+
    "\3\0\1\u0131\27\31\24\0\2\31\6\0\2\31\3\0"+
    "\1\u0132\27\31\24\0\2\31\6\0\2\31\3\0\10\31"+
    "\1\u0133\17\31\24\0\2\31\6\0\2\31\3\0\15\31"+
    "\1\u0134\12\31\24\0\2\31\6\0\2\31\3\0\16\31"+
    "\1\u0135\11\31\24\0\2\31\6\0\2\31\3\0\3\31"+
    "\1\u0136\24\31\24\0\2\31\6\0\2\31\3\0\4\31"+
    "\1\u0137\23\31\24\0\2\31\6\0\2\31\3\0\4\31"+
    "\1\u0138\23\31\24\0\2\31\6\0\2\31\3\0\22\31"+
    "\1\u0139\5\31\24\0\2\31\6\0\2\31\3\0\3\31"+
    "\1\u013a\24\31\24\0\2\31\6\0\2\31\3\0\2\31"+
    "\1\u013b\25\31\24\0\2\31\6\0\2\31\3\0\10\31"+
    "\1\u013c\17\31\24\0\2\31\6\0\2\31\3\0\22\31"+
    "\1\u013d\5\31\24\0\2\31\6\0\2\31\3\0\10\31"+
    "\1\u013e\17\31\24\0\2\31\6\0\2\31\3\0\16\31"+
    "\1\u013f\11\31\24\0\2\31\6\0\2\31\3\0\2\31"+
    "\1\u0140\25\31\24\0\2\31\6\0\2\31\3\0\4\31"+
    "\1\u0141\23\31\24\0\2\31\6\0\2\31\3\0\13\31"+
    "\1\u0142\14\31\24\0\2\31\6\0\2\31\3\0\13\31"+
    "\1\u0143\14\31\24\0\2\31\6\0\2\31\3\0\2\31"+
    "\1\u0144\25\31\24\0\2\31\6\0\2\31\3\0\13\31"+
    "\1\u0145\14\31\24\0\2\31\6\0\2\31\3\0\22\31"+
    "\1\u0146\5\31\24\0\2\31\6\0\2\31\3\0\4\31"+
    "\1\u0147\23\31\24\0\2\31\6\0\2\31\3\0\20\31"+
    "\1\u0148\7\31\24\0\2\31\6\0\2\31\3\0\4\31"+
    "\1\u0149\23\31\24\0\2\31\6\0\2\31\3\0\4\31"+
    "\1\u014a\23\31\24\0\2\31\6\0\2\31\3\0\1\u014b"+
    "\27\31\24\0\2\31\6\0\2\31\3\0\16\31\1\u014c"+
    "\11\31\24\0\2\31\6\0\2\31\3\0\15\31\1\u014d"+
    "\12\31\24\0\2\31\6\0\2\31\3\0\22\31\1\u014e"+
    "\5\31\24\0\2\31\6\0\2\31\3\0\10\31\1\u014f"+
    "\17\31\24\0\2\31\6\0\2\31\3\0\4\31\1\u0150"+
    "\23\31\24\0\2\31\6\0\2\31\3\0\3\31\1\u0151"+
    "\24\31\24\0\2\31\6\0\2\31\3\0\21\31\1\u0152"+
    "\6\31\24\0\2\31\6\0\2\31\3\0\15\31\1\u0153"+
    "\12\31\24\0\2\31\6\0\2\31\3\0\16\31\1\u0154"+
    "\11\31\24\0\2\31\6\0\2\31\3\0\15\31\1\u0155"+
    "\12\31\24\0\2\31\6\0\2\31\3\0\20\31\1\u0156"+
    "\7\31\24\0\2\31\6\0\2\31\3\0\4\31\1\u0157"+
    "\23\31\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14364];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\6\11\5\1\1\11"+
    "\5\1\2\11\20\1\1\11\1\1\1\11\1\1\2\0"+
    "\2\11\1\0\1\11\4\1\1\11\1\0\4\1\2\11"+
    "\1\1\3\11\51\1\6\11\1\1\2\0\2\1\1\11"+
    "\3\1\1\11\56\1\1\0\1\11\1\0\1\11\1\0"+
    "\246\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[343];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private Symbol token(int type) {
    return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
  }

  private Symbol token(int type, Object value) {
    return new Symbol(type, yyline + 1, yycolumn + 1, value);
  }

  private Symbol reportError(String tipo, String descripcion) {
    ManejoErrores.agregar(new ErrorLexico(tipo, yytext(), yyline + 1, yycolumn + 1, descripcion));
    return token(sym.ERROR, yytext());
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerJava(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return reportError("CARACTER_NO_RECONOCIDO", "Carácter no pertenece al lenguaje");
            }
          // fall through
          case 111: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 112: break;
          case 3:
            { return token(sym.NOT);
            }
          // fall through
          case 113: break;
          case 4:
            { return token(sym.MOD);
            }
          // fall through
          case 114: break;
          case 5:
            { return reportError("CARACTER_MAL_FORMADO", "Literal de carácter inválido o sin cerrar");
            }
          // fall through
          case 115: break;
          case 6:
            { return token(sym.LPAREN);
            }
          // fall through
          case 116: break;
          case 7:
            { return token(sym.RPAREN);
            }
          // fall through
          case 117: break;
          case 8:
            { return token(sym.MULT);
            }
          // fall through
          case 118: break;
          case 9:
            { return token(sym.PLUS);
            }
          // fall through
          case 119: break;
          case 10:
            { return token(sym.COMMA);
            }
          // fall through
          case 120: break;
          case 11:
            { return token(sym.MINUS);
            }
          // fall through
          case 121: break;
          case 12:
            { return token(sym.DOT);
            }
          // fall through
          case 122: break;
          case 13:
            { return token(sym.DIV);
            }
          // fall through
          case 123: break;
          case 14:
            { return token(sym.INT_LITERAL, yytext());
            }
          // fall through
          case 124: break;
          case 15:
            { return token(sym.COLON);
            }
          // fall through
          case 125: break;
          case 16:
            { return token(sym.SEMICOLON);
            }
          // fall through
          case 126: break;
          case 17:
            { return token(sym.LT);
            }
          // fall through
          case 127: break;
          case 18:
            { return token(sym.EQ);
            }
          // fall through
          case 128: break;
          case 19:
            { return token(sym.GT);
            }
          // fall through
          case 129: break;
          case 20:
            { return token(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 130: break;
          case 21:
            { return token(sym.LBRACK);
            }
          // fall through
          case 131: break;
          case 22:
            { return token(sym.RBRACK);
            }
          // fall through
          case 132: break;
          case 23:
            { return token(sym.LBRACE);
            }
          // fall through
          case 133: break;
          case 24:
            { return token(sym.RBRACE);
            }
          // fall through
          case 134: break;
          case 25:
            { return token(sym.NEQ);
            }
          // fall through
          case 135: break;
          case 26:
            { String lexemaLimpio = yytext().trim();
    ManejoErrores.agregar(new ErrorLexico("CADENA_MAL_FORMADA", lexemaLimpio, yyline + 1, yycolumn + 1, "Cadena de texto sin cerrar comillas en la misma línea"));
    return token(sym.ERROR, lexemaLimpio);
            }
          // fall through
          case 136: break;
          case 27:
            { return token(sym.STRING_LITERAL, yytext());
            }
          // fall through
          case 137: break;
          case 28:
            { return token(sym.AND);
            }
          // fall through
          case 138: break;
          case 29:
            { return token(sym.RANGE);
            }
          // fall through
          case 139: break;
          case 30:
            { return reportError("NUMERO_INVALIDO", "Flotante incompleto, falta parte decimal");
            }
          // fall through
          case 140: break;
          case 31:
            { return reportError("NUMERO_INVALIDO", "Literal numérico octal o cero inicial no permitido");
            }
          // fall through
          case 141: break;
          case 32:
            { return reportError("IDENTIFICADOR_INVALIDO", "El identificador no puede iniciar con números");
            }
          // fall through
          case 142: break;
          case 33:
            { return token(sym.DOUBLE_COLON);
            }
          // fall through
          case 143: break;
          case 34:
            { return token(sym.LE);
            }
          // fall through
          case 144: break;
          case 35:
            { return token(sym.EQEQ);
            }
          // fall through
          case 145: break;
          case 36:
            { return token(sym.GE);
            }
          // fall through
          case 146: break;
          case 37:
            { return token(sym.SAFE_CALL);
            }
          // fall through
          case 147: break;
          case 38:
            { return token(sym.ELVIS);
            }
          // fall through
          case 148: break;
          case 39:
            { return token(sym.AS);
            }
          // fall through
          case 149: break;
          case 40:
            { return token(sym.DO);
            }
          // fall through
          case 150: break;
          case 41:
            { return token(sym.IF);
            }
          // fall through
          case 151: break;
          case 42:
            { return token(sym.IN);
            }
          // fall through
          case 152: break;
          case 43:
            { return token(sym.IS);
            }
          // fall through
          case 153: break;
          case 44:
            { return token(sym.OR);
            }
          // fall through
          case 154: break;
          case 45:
            { return token(sym.NEQEQEQ);
            }
          // fall through
          case 155: break;
          case 46:
            { return token(sym.NOT_IN);
            }
          // fall through
          case 156: break;
          case 47:
            { return token(sym.NOT_IS);
            }
          // fall through
          case 157: break;
          case 48:
            { return token(sym.CHAR_LITERAL, yytext());
            }
          // fall through
          case 158: break;
          case 49:
            { return token(sym.FLOAT_LITERAL, yytext());
            }
          // fall through
          case 159: break;
          case 50:
            { return token(sym.EQEQEQ);
            }
          // fall through
          case 160: break;
          case 51:
            { return token(sym.AS_SAFE);
            }
          // fall through
          case 161: break;
          case 52:
            { return token(sym.FOR);
            }
          // fall through
          case 162: break;
          case 53:
            { return token(sym.FUN);
            }
          // fall through
          case 163: break;
          case 54:
            { return token(sym.OUT);
            }
          // fall through
          case 164: break;
          case 55:
            { return token(sym.TRY);
            }
          // fall through
          case 165: break;
          case 56:
            { return token(sym.VAL);
            }
          // fall through
          case 166: break;
          case 57:
            { return token(sym.VAR);
            }
          // fall through
          case 167: break;
          case 58:
            { return token(sym.DATA);
            }
          // fall through
          case 168: break;
          case 59:
            { return token(sym.ELSE);
            }
          // fall through
          case 169: break;
          case 60:
            { return token(sym.ENUM);
            }
          // fall through
          case 170: break;
          case 61:
            { return token(sym.INIT);
            }
          // fall through
          case 171: break;
          case 62:
            { return token(sym.NULL);
            }
          // fall through
          case 172: break;
          case 63:
            { return token(sym.OPEN);
            }
          // fall through
          case 173: break;
          case 64:
            { return token(sym.THIS);
            }
          // fall through
          case 174: break;
          case 65:
            { return token(sym.TRUE, yytext());
            }
          // fall through
          case 175: break;
          case 66:
            { return token(sym.WHEN);
            }
          // fall through
          case 176: break;
          case 67:
            { return reportError("NUMERO_INVALIDO", "Formato numérico inválido con múltiples puntos");
            }
          // fall through
          case 177: break;
          case 68:
            { return token(sym.BREAK);
            }
          // fall through
          case 178: break;
          case 69:
            { return token(sym.CATCH);
            }
          // fall through
          case 179: break;
          case 70:
            { return token(sym.CLASS);
            }
          // fall through
          case 180: break;
          case 71:
            { return token(sym.CONST);
            }
          // fall through
          case 181: break;
          case 72:
            { return token(sym.FALSE);
            }
          // fall through
          case 182: break;
          case 73:
            { return token(sym.FINAL);
            }
          // fall through
          case 183: break;
          case 74:
            { return token(sym.INFIX);
            }
          // fall through
          case 184: break;
          case 75:
            { return token(sym.INNER);
            }
          // fall through
          case 185: break;
          case 76:
            { return token(sym.SUPER);
            }
          // fall through
          case 186: break;
          case 77:
            { return token(sym.THROW);
            }
          // fall through
          case 187: break;
          case 78:
            { return token(sym.VALUE);
            }
          // fall through
          case 188: break;
          case 79:
            { return token(sym.WHERE);
            }
          // fall through
          case 189: break;
          case 80:
            { return token(sym.WHILE);
            }
          // fall through
          case 190: break;
          case 81:
            { return token(sym.ACTUAL);
            }
          // fall through
          case 191: break;
          case 82:
            { return token(sym.EXPECT);
            }
          // fall through
          case 192: break;
          case 83:
            { return token(sym.IMPORT);
            }
          // fall through
          case 193: break;
          case 84:
            { return token(sym.INLINE);
            }
          // fall through
          case 194: break;
          case 85:
            { return token(sym.OBJECT);
            }
          // fall through
          case 195: break;
          case 86:
            { return token(sym.PUBLIC);
            }
          // fall through
          case 196: break;
          case 87:
            { return token(sym.RETURN);
            }
          // fall through
          case 197: break;
          case 88:
            { return token(sym.SEALED);
            }
          // fall through
          case 198: break;
          case 89:
            { return token(sym.TYPEOF);
            }
          // fall through
          case 199: break;
          case 90:
            { return token(sym.VARARG);
            }
          // fall through
          case 200: break;
          case 91:
            { return token(sym.FINALLY);
            }
          // fall through
          case 201: break;
          case 92:
            { return token(sym.PACKAGE);
            }
          // fall through
          case 202: break;
          case 93:
            { return token(sym.PRIVATE);
            }
          // fall through
          case 203: break;
          case 94:
            { return token(sym.SUSPEND);
            }
          // fall through
          case 204: break;
          case 95:
            { return token(sym.TAILREC);
            }
          // fall through
          case 205: break;
          case 96:
            { return token(sym.ABSTRACT);
            }
          // fall through
          case 206: break;
          case 97:
            { return token(sym.CONTINUE);
            }
          // fall through
          case 207: break;
          case 98:
            { return token(sym.EXTERNAL);
            }
          // fall through
          case 208: break;
          case 99:
            { return token(sym.INTERNAL);
            }
          // fall through
          case 209: break;
          case 100:
            { return token(sym.LATEINIT);
            }
          // fall through
          case 210: break;
          case 101:
            { return token(sym.NOINLINE);
            }
          // fall through
          case 211: break;
          case 102:
            { return token(sym.OPERATOR);
            }
          // fall through
          case 212: break;
          case 103:
            { return token(sym.OVERRIDE);
            }
          // fall through
          case 213: break;
          case 104:
            { return token(sym.COMPANION);
            }
          // fall through
          case 214: break;
          case 105:
            { return token(sym.INTERFACE);
            }
          // fall through
          case 215: break;
          case 106:
            { return token(sym.PROTECTED);
            }
          // fall through
          case 216: break;
          case 107:
            { return token(sym.TYPEALIAS);
            }
          // fall through
          case 217: break;
          case 108:
            { return token(sym.ANNOTATION);
            }
          // fall through
          case 218: break;
          case 109:
            { return token(sym.CONSTRUCTOR);
            }
          // fall through
          case 219: break;
          case 110:
            { return token(sym.CROSSINLINE);
            }
          // fall through
          case 220: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
