
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act1_lexico;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserJava extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserJava() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserJava(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserJava(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\002\003" +
    "\000\002\003\005\000\002\003\005\000\002\004\004\000" +
    "\002\004\003\000\002\005\005\000\002\005\005\000\002" +
    "\007\003\000\002\007\005\000\002\006\006\000\002\006" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\012\003\011\004\006\005\013\006\014\001" +
    "\002\000\004\002\042\001\002\000\004\002\ufffd\001\002" +
    "\000\006\003\036\150\023\001\002\000\006\005\ufff8\006" +
    "\ufff8\001\002\000\006\005\013\006\014\001\002\000\004" +
    "\002\ufffc\001\002\000\006\005\013\006\014\001\002\000" +
    "\006\003\022\150\023\001\002\000\006\003\015\150\016" +
    "\001\002\000\004\136\021\001\002\000\004\135\017\001" +
    "\002\000\004\136\020\001\002\000\004\002\ufff3\001\002" +
    "\000\004\002\ufff2\001\002\000\004\142\030\001\002\000" +
    "\006\142\ufff5\143\ufff5\001\002\000\006\142\025\143\026" +
    "\001\002\000\006\005\ufff7\006\ufff7\001\002\000\004\150" +
    "\027\001\002\000\006\142\ufff4\143\ufff4\001\002\000\006" +
    "\005\ufff6\006\ufff6\001\002\000\004\002\uffff\001\002\000" +
    "\006\005\ufff9\006\ufff9\001\002\000\004\002\ufffe\001\002" +
    "\000\006\005\013\006\014\001\002\000\004\002\000\001" +
    "\002\000\004\142\041\001\002\000\006\142\040\143\026" +
    "\001\002\000\006\005\ufffb\006\ufffb\001\002\000\006\005" +
    "\ufffa\006\ufffa\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\014\002\003\003\007\004\011\005\006\006" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\036\001\001\000\002\001\001\000\010\004\033\005" +
    "\006\006\032\001\001\000\002\001\001\000\006\005\031" +
    "\006\030\001\001\000\004\007\023\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\031" +
    "\006\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserJava$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserJava$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserJava$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    @Override
    public void syntax_error(Symbol s) {
        if (s.left >= 0) {
            System.err.println("Error sintactico en linea " + s.left + 
                               ", columna " + s.right + ": se encontro '" + s.value + "'");
        }
    }

    @Override
    public void unrecovered_syntax_error(Symbol s) {
        if (s.left >= 0) {
            System.err.println("Error fatal en linea " + s.left + 
                               ", columna " + s.right + ": se encontro '" + s.value + "'");
        }
        System.err.println("El analisis no puede continuar. Abortando...");
        System.exit(1);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserJava$actions {
  private final ParserJava parser;

  /** Constructor */
  CUP$ParserJava$actions(ParserJava parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserJava$do_action_part00000000(
    int                        CUP$ParserJava$act_num,
    java_cup.runtime.lr_parser CUP$ParserJava$parser,
    java.util.Stack            CUP$ParserJava$stack,
    int                        CUP$ParserJava$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserJava$result;

      /* select the action based on the action number */
      switch (CUP$ParserJava$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		RESULT = start_val;
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserJava$parser.done_parsing();
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= estructura_paquete lista_importaciones clase_principal 
            {
              Object RESULT =null;
		 System.out.println("Analisis sintactico finalizado correctamente\n"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= lista_importaciones clase_principal 
            {
              Object RESULT =null;
		 System.out.println("Analisis sintactico finalizado correctamente (Sin paquete)\n"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= estructura_paquete clase_principal 
            {
              Object RESULT =null;
		 System.out.println("Analisis sintactico finalizado correctamente (Sin imports)\n"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= clase_principal 
            {
              Object RESULT =null;
		 System.out.println("Analisis sintactico finalizado correctamente (Solo clase)\n"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // programa ::= error 
            {
              Object RESULT =null;
		 parser.unrecovered_syntax_error(cur_token); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // estructura_paquete ::= PACKAGE ruta SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println("Paquete reconocido correctamente"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("estructura_paquete",1, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // estructura_paquete ::= PACKAGE error SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println("-> [Recuperacion] Se ignoro error en paquete hasta el ';'"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("estructura_paquete",1, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_importaciones ::= lista_importaciones importacion 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_importaciones",2, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_importaciones ::= importacion 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_importaciones",2, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // importacion ::= IMPORT ruta SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println("Importacion reconocida correctamente"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // importacion ::= IMPORT error SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println("-> [Recuperacion] Se ignoro error en importacion hasta el ';'"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ruta ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("ruta",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ruta ::= ruta DOT IDENTIFIER 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("ruta",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // clase_principal ::= CLASS IDENTIFIER LBRACE RBRACE 
            {
              Object RESULT =null;
		 System.out.println("Clase principal reconocida correctamente. Estructura de llaves valida."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("clase_principal",4, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // clase_principal ::= CLASS error RBRACE 
            {
              Object RESULT =null;
		 System.out.println("-> [Recuperacion] Error en definicion de clase. Se omitio hasta '}'"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("clase_principal",4, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserJava$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserJava$do_action(
    int                        CUP$ParserJava$act_num,
    java_cup.runtime.lr_parser CUP$ParserJava$parser,
    java.util.Stack            CUP$ParserJava$stack,
    int                        CUP$ParserJava$top)
    throws java.lang.Exception
    {
              return CUP$ParserJava$do_action_part00000000(
                               CUP$ParserJava$act_num,
                               CUP$ParserJava$parser,
                               CUP$ParserJava$stack,
                               CUP$ParserJava$top);
    }
}

}
