
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act1_lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 52;
  public static final int IDENTIFIER = 113;
  public static final int INTERNAL = 28;
  public static final int GT = 92;
  public static final int TYPEOF = 9;
  public static final int RECEIVER = 69;
  public static final int GETTER = 66;
  public static final int CONST = 49;
  public static final int INT_LITERAL = 114;
  public static final int PARAM = 70;
  public static final int DOUBLE_COLON = 102;
  public static final int GE = 93;
  public static final int DYNAMIC = 78;
  public static final int GET = 62;
  public static final int DELEGATE = 72;
  public static final int PROPERTY = 68;
  public static final int CONSTRUCTOR = 73;
  public static final int ENUM = 35;
  public static final int RBRACK = 108;
  public static final int ACTUAL = 77;
  public static final int CROSSINLINE = 43;
  public static final int INIT = 74;
  public static final int LATEINIT = 46;
  public static final int NOT_IS = 51;
  public static final int COMMA = 109;
  public static final int CATCH = 22;
  public static final int DOUBLE_LITERAL = 117;
  public static final int RBRACE = 106;
  public static final int NEQEQEQ = 95;
  public static final int THROW = 24;
  public static final int RPAREN = 104;
  public static final int INNER = 36;
  public static final int NOT_IN = 55;
  public static final int EQEQEQ = 94;
  public static final int LBRACK = 107;
  public static final int LT = 90;
  public static final int LBRACE = 105;
  public static final int LPAREN = 103;
  public static final int OUT = 81;
  public static final int PROTECTED = 27;
  public static final int NOT = 98;
  public static final int FALSE = 60;
  public static final int TAILREC = 44;
  public static final int LE = 91;
  public static final int COMPANION = 75;
  public static final int OBJECT = 7;
  public static final int ERROR = 120;
  public static final int VAR = 3;
  public static final int OVERRIDE = 32;
  public static final int FINAL = 30;
  public static final int INLINE = 41;
  public static final int PACKAGE = 19;
  public static final int VAL = 2;
  public static final int EXTERNAL = 45;
  public static final int EQ = 87;
  public static final int MOD = 86;
  public static final int WHEN = 12;
  public static final int REIFIED = 79;
  public static final int CLASS = 5;
  public static final int SUPER = 57;
  public static final int ABSTRACT = 29;
  public static final int TRUE = 59;
  public static final int LONG_LITERAL = 115;
  public static final int PLUS = 82;
  public static final int WHILE = 13;
  public static final int INTERFACE = 6;
  public static final int DO = 15;
  public static final int FOR = 14;
  public static final int DIV = 85;
  public static final int VARARG = 47;
  public static final int MULT = 84;
  public static final int PUBLIC = 25;
  public static final int RETURN = 16;
  public static final int SETPARAM = 71;
  public static final int ELSE = 11;
  public static final int TRY = 21;
  public static final int BREAK = 17;
  public static final int FUN = 4;
  public static final int DOT = 111;
  public static final int STRING_LITERAL = 119;
  public static final int SAFE_CALL = 99;
  public static final int EQEQ = 88;
  public static final int NULL = 58;
  public static final int SEMICOLON = 110;
  public static final int EOF = 0;
  public static final int WHERE = 80;
  public static final int THIS = 56;
  public static final int SEALED = 33;
  public static final int OPERATOR = 40;
  public static final int IMPORT = 20;
  public static final int MINUS = 83;
  public static final int IS = 50;
  public static final int SUSPEND = 48;
  public static final int FLOAT_LITERAL = 116;
  public static final int NOINLINE = 42;
  public static final int IN = 54;
  public static final int OR = 97;
  public static final int SET = 63;
  public static final int error = 1;
  public static final int DATA = 34;
  public static final int FINALLY = 23;
  public static final int INFIX = 39;
  public static final int CONTINUE = 18;
  public static final int ANNOTATION = 38;
  public static final int IF = 10;
  public static final int AS_SAFE = 53;
  public static final int COLON = 112;
  public static final int BY = 61;
  public static final int FILE = 65;
  public static final int SETTER = 67;
  public static final int FIELD = 64;
  public static final int EXPECT = 76;
  public static final int CHAR_LITERAL = 118;
  public static final int TYPEALIAS = 8;
  public static final int RANGE = 101;
  public static final int NEQ = 89;
  public static final int AND = 96;
  public static final int VALUE = 37;
  public static final int OPEN = 31;
  public static final int PRIVATE = 26;
  public static final int ELVIS = 100;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAL",
  "VAR",
  "FUN",
  "CLASS",
  "INTERFACE",
  "OBJECT",
  "TYPEALIAS",
  "TYPEOF",
  "IF",
  "ELSE",
  "WHEN",
  "WHILE",
  "FOR",
  "DO",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "PACKAGE",
  "IMPORT",
  "TRY",
  "CATCH",
  "FINALLY",
  "THROW",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "INTERNAL",
  "ABSTRACT",
  "FINAL",
  "OPEN",
  "OVERRIDE",
  "SEALED",
  "DATA",
  "ENUM",
  "INNER",
  "VALUE",
  "ANNOTATION",
  "INFIX",
  "OPERATOR",
  "INLINE",
  "NOINLINE",
  "CROSSINLINE",
  "TAILREC",
  "EXTERNAL",
  "LATEINIT",
  "VARARG",
  "SUSPEND",
  "CONST",
  "IS",
  "NOT_IS",
  "AS",
  "AS_SAFE",
  "IN",
  "NOT_IN",
  "THIS",
  "SUPER",
  "NULL",
  "TRUE",
  "FALSE",
  "BY",
  "GET",
  "SET",
  "FIELD",
  "FILE",
  "GETTER",
  "SETTER",
  "PROPERTY",
  "RECEIVER",
  "PARAM",
  "SETPARAM",
  "DELEGATE",
  "CONSTRUCTOR",
  "INIT",
  "COMPANION",
  "EXPECT",
  "ACTUAL",
  "DYNAMIC",
  "REIFIED",
  "WHERE",
  "OUT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "EQ",
  "EQEQ",
  "NEQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQEQEQ",
  "NEQEQEQ",
  "AND",
  "OR",
  "NOT",
  "SAFE_CALL",
  "ELVIS",
  "RANGE",
  "DOUBLE_COLON",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "SEMICOLON",
  "DOT",
  "COLON",
  "IDENTIFIER",
  "INT_LITERAL",
  "LONG_LITERAL",
  "FLOAT_LITERAL",
  "DOUBLE_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "ERROR"
  };
}

